### ISSUE TITLE
Tried to register two views with the same name

### ISSUE THREAD

**Issue by enzzoperez** [react-native-community/react-native-picker#15] opened 2019-08-15 18:57 UTC
# Bug
I tried to add the picker, the compilation is fine, but when the app is open appears a red screen with the message: 
**Tried to register two views with the same name AndroidDropdownPicker**

Update: I also use Native base in the project
Can you help me please?

## Environment info
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 696.37 MB / 7.68 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
      Yarn: 1.15.2 - /usr/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 20, 22, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

React native info output:

```bash
 // Tried to register two views with the same name AndroidDropdownPicker
```

Library version: 0.59.9

**Comment by Akhnaten972** [comment] 2019-08-18 20:35
+1

**Comment by danieljgp2** [comment] 2019-09-05 20:29
Im facing this error too, this error seems to be related with the dependencies, there is probably a dependency working with the picker of react-native. 

Any idea about how to fix it @jainkuniya ?

**Comment by jainkuniya** [comment] 2019-09-05 20:37
Hi @danieljgp2, thanks for the report. Will look into it. It will  be great if you could share some code snippet, through which it is easily reproducible

**Comment by danieljgp2** [comment] 2019-09-05 20:55
@jainkuniya which react native version are you using as a dependecy ? i dont know if the problem is related to any dependecy of my project or any dependency of the library but im pretty sure that problem is related with the changes of RN version after 0.59 and the deprecation of the Picker.

**Comment by sofiageo** [comment] 2019-10-31 23:41
I ran into this issue. For me it was caused by a wrong import on my project, which was looking for react-native Picker. But what I noticed is that even on react-native 0.61.2 package, this [PR](https://github.com/facebook/react-native/pull/25899/files) was not included. Maybe it's fixed in the new version (0.61.3)

**Comment by Sroka** [comment] 2019-12-18 14:46
Any news on this? I have the same problem and cannot get rid of it :/ @sofiageo How did you manage to figure out where offending react-native Picker import was? I check my whole app and there are no usages of Picker. Tried to search in node_nodules to check if some lib uses it but no luck

**Comment by sofiageo** [comment] 2019-12-18 16:14
> Any news on this? I have the same problem and cannot get rid of it :/ @sofiageo How did you manage to figure out where offending react-native Picker import was? I check my whole app and there are no usages of Picker. Tried to search in node_nodules to check if some lib uses it but no luck

It was easy for me because I only had 2 imports of Picker. How are you searching in node_modules? If it is a multi-import from react-native you will have to only search for the word Picker.

**Comment by chakrihacker** [comment] 2020-01-03 12:41
Is this bug still exists??

**Comment by danieljgp2** [comment] 2020-01-03 14:02
@chakrihacker Probably it does, the bug is caused when a dependency imports the picker from react-native and you import the picker from react-native-community/picker

**Comment by chakrihacker** [comment] 2020-01-03 18:44
@danieljgp2 The Android native view name is changed to RNCPicker from RCTPicker but previous versions have name RCTPicker. I think by updating dependency this issue will be solved.

**Closed by chakrihacker** 2020-01-03 18:44 UTC

**Comment by sislovesmedotcom** [comment] 2020-04-22 08:31
+1

Library version: 0.59.9

<img width="339" alt="Screen Shot 2020-04-22 at 4 31 07 PM" src="https://user-images.githubusercontent.com/39583750/79959408-b2637c00-84b6-11ea-9006-f9352db1a740.png">

**Comment by orion151** [comment] 2020-04-22 18:33
I have same issue.
"react-native": "0.62.2",
"@react-native-community/picker": "^1.3.0",

please solve this proble

**Comment by chakrihacker** [comment] 2020-04-23 02:57
Is this happening in new rn versions?

**Comment by rohan-develop** [comment] 2020-04-23 22:06
> Is this happening in new rn versions?

yes , i am using   "@react-native-community/picker": "^1.3.0", showing 'Invariant Violation'

**Comment by orion151** [comment] 2020-04-23 23:01
I found why this error occurs.

**Comment by rohan-develop** [comment] 2020-04-24 02:02
> I found why this error occurs.

Is there any required field we are missing?

**Comment by orion151** [comment] 2020-04-24 07:41
Can you share your package.json file?

**Comment by orion151** [comment] 2020-04-24 07:49
In my case, I used @react-native-community/picker": "^1.3.0   and   "react-native-google-places-autocomplete": "^1.4.1" in my project.
"react-native-google-places-autocomplete": "^1.4.1" used picker from react-native.
so, occured this error.
Perhaps, there are another pakage using picker from react-native  like this in your project.

**Comment by khalednailigit** [comment] 2020-04-24 14:21
+1

**Comment by KawaljeetSBagga** [comment] 2020-04-27 11:35
@orion151  How did you get rid of this?

**Comment by hussainhspl** [comment] 2020-04-29 07:43
> @danieljgp2 The Android native view name is changed to RNCPicker from RCTPicker but previous versions have name RCTPicker. I think by updating dependency this issue will be solved.

how to update dependency ?

**Comment by hussainhspl** [comment] 2020-04-29 09:24
> Is this happening in new rn versions?

yes i am using RN 0.62 app is not running and getting crashed,
and also using native base 2.13.12 version and rn picker  ver 1.3.0

**Comment by rpCal** [comment] 2020-04-30 07:22
On my code setup...
```
 <Picker
  selectedValue={formik.values.gender}
  accessibilityLabel={'gender'}
  onValueChange={(itemValue, itemIndex) => {
    formik.setFieldValue('gender', itemValue);
  }}>
  <Picker.Item label="Male" value="MALE" />
  <Picker.Item label="Female" value="FEMALE" />
</Picker>
```
Issue is related to field accessibilityLabel... If key is setup with any value = err!

**Comment by alorr10** [comment] 2020-05-01 20:07
Seeing this as well

"@react-native-community/picker": "^1.3.0",
 "react-native-google-places-autocomplete": "^1.4.1",

Any fixes?

**Comment by jafaronly** [comment] 2020-05-05 14:26
if anyone still has this issue, make sure that you don't use "Picker" from an other package in my case it was "styled-components"

**Comment by MrNoino** [comment] 2020-05-06 21:40
I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.

**Comment by rohan-yadav007** [comment] 2020-05-07 04:49
> I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.

But what when we have to show picker item dynamically through api...

**Comment by MrNoino** [comment] 2020-05-07 13:57
> > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> 
> But what when we have to show picker item dynamically through api...

You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.

**Comment by iYahya** [comment] 2020-05-07 13:59
> > > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> > 
> > 
> > But what when we have to show picker item dynamically through api...
> 
> You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.

could you attach a screenshot of your solution ?

**Comment by MrNoino** [comment] 2020-05-07 14:20
> > > > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> > > 
> > > 
> > > But what when we have to show picker item dynamically through api...
> > 
> > 
> > You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.
> 
> could you attach a screenshot of your solution ?

![Picker](https://user-images.githubusercontent.com/62909686/81305266-0739f180-9076-11ea-899e-eaffa69bc1d0.PNG)

PS: I use functions to render the elements so if you use class to render, you should realize that "onValueChange" and "selectedValue" work diferent.

**Comment by rohan-yadav007** [comment] 2020-05-09 06:40
> > > > > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> > > > 
> > > > 
> > > > But what when we have to show picker item dynamically through api...
> > > 
> > > 
> > > You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.
> > 
> > 
> > could you attach a screenshot of your solution ?
> 
> ![Picker](https://user-images.githubusercontent.com/62909686/81305266-0739f180-9076-11ea-899e-eaffa69bc1d0.PNG)
> 
> PS: I use functions to render the elements so if you use class to render, you should realize that "onValueChange" and "selectedValue" work diferent.

I am using class component and using a single dropdown, still getting error. Then i added accessibility as you suggested, still getting same error

**Comment by MrNoino** [comment] 2020-05-09 22:31
> > > > > > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> > > > > 
> > > > > 
> > > > > But what when we have to show picker item dynamically through api...
> > > > 
> > > > 
> > > > You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.
> > > 
> > > 
> > > could you attach a screenshot of your solution ?
> > 
> > 
> > ![Picker](https://user-images.githubusercontent.com/62909686/81305266-0739f180-9076-11ea-899e-eaffa69bc1d0.PNG)
> > PS: I use functions to render the elements so if you use class to render, you should realize that "onValueChange" and "selectedValue" work diferent.
> 
> I am using class component and using a single dropdown, still getting error. Then i added accessibility as you suggested, still getting same error

If your error like me is "Tried to resgister two views with the same name AndroidDropdowPicker" like above in screenshoot uploaded by @sislovesmedotcom, you should have at least 2 Pickers because this error is about having the same name (accessibilityLabel) for two or more Pickers. Make sure if you have only one Picker in all Project or atributte diferents values to accessibilityLabel in case you have more than one dropdown. The reason why you have to attibute diferents values to accessibilityLabel is because react native attribute a default value that is equal for every Pickers.

**Comment by rohan-yadav007** [comment] 2020-05-09 23:03
> > > > > > > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> > > > > > 
> > > > > > 
> > > > > > But what when we have to show picker item dynamically through api...
> > > > > 
> > > > > 
> > > > > You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.
> > > > 
> > > > 
> > > > could you attach a screenshot of your solution ?
> > > 
> > > 
> > > ![Picker](https://user-images.githubusercontent.com/62909686/81305266-0739f180-9076-11ea-899e-eaffa69bc1d0.PNG)
> > > PS: I use functions to render the elements so if you use class to render, you should realize that "onValueChange" and "selectedValue" work diferent.
> > 
> > 
> > I am using class component and using a single dropdown, still getting error. Then i added accessibility as you suggested, still getting same error
> 
> If your error like me is "Tried to resgister two views with the same name AndroidDropdowPicker" like above in screenshoot uploaded by @sislovesmedotcom, you should have at least 2 Pickers because this error is about having the same name (accessibilityLabel) for two or more Pickers. Make sure if you have only one Picker in all Project or atributte diferents values to accessibilityLabel in case you have more than one dropdown. The reason why you have to attibute diferents values to accessibilityLabel is because react native attribute a default value that is equal for every Pickers.

As soon as i import Picker it show error even if i am not using a single drop-down.  I think problem lies within the npm package because i get this error just after importing. I am using RN 0.62. Hence it supports autolinking but after getting error several times i thought may be issue is due to bad linking hence tried manual linking. But it didn't help

**Comment by MrNoino** [comment] 2020-05-09 23:28
> > > > > > > > I have 3 Pickers in one screen and I solve the same problem as you by adding accessibilityLabel={'pickername'} in all 3 Pickers, with diferent values.
> > > > > > > 
> > > > > > > 
> > > > > > > But what when we have to show picker item dynamically through api...
> > > > > > 
> > > > > > 
> > > > > > You should use "accessibilityLabel={'pickername'}" in Picker atributes and generate picker items dinamycally unless you have to generate picker dinamically as well.
> > > > > 
> > > > > 
> > > > > could you attach a screenshot of your solution ?
> > > > 
> > > > 
> > > > ![Picker](https://user-images.githubusercontent.com/62909686/81305266-0739f180-9076-11ea-899e-eaffa69bc1d0.PNG)
> > > > PS: I use functions to render the elements so if you use class to render, you should realize that "onValueChange" and "selectedValue" work diferent.
> > > 
> > > 
> > > I am using class component and using a single dropdown, still getting error. Then i added accessibility as you suggested, still getting same error
> > 
> > 
> > If your error like me is "Tried to resgister two views with the same name AndroidDropdowPicker" like above in screenshoot uploaded by @sislovesmedotcom, you should have at least 2 Pickers because this error is about having the same name (accessibilityLabel) for two or more Pickers. Make sure if you have only one Picker in all Project or atributte diferents values to accessibilityLabel in case you have more than one dropdown. The reason why you have to attibute diferents values to accessibilityLabel is because react native attribute a default value that is equal for every Pickers.
> 
> As soon as i import Picker it show error even if i am not using a single drop-down. I think problem lies within the npm package because i get this error just after importing. I am using RN 0.62. Hence it supports autolinking but after getting error several times i thought may be issue is due to bad linking hence tried manual linking. But it didn't help

I assume you import  "@react-native-community/picker" because the same problem as I, receiving a warning telling that Picker will be descontinued from react-native. I installed this library and I didn't need to  linking manually. Then became this error and I fixed by implement the solution  that I shared here.
So, my advice to you is reinstall the library and check if you are getting that error yet.

**Comment by rohan-yadav007** [comment] 2020-05-10 21:01
Finally i found my fixes, I am using styled component in my project, hence to customize picker I used  picker into styled to add styling
![Capture](https://user-images.githubusercontent.com/53953445/81510461-755d0d80-932f-11ea-9c17-1d402421b403.PNG)

**Comment by MrNoino** [comment] 2020-05-10 22:47
> Finally i found my fixes, I am using styled component in my project, hence to customize picker I used picker into styled to add styling
> ![Capture](https://user-images.githubusercontent.com/53953445/81510461-755d0d80-932f-11ea-9c17-1d402421b403.PNG)
> 
> After removing this, i get rid of error

I'm glad you fixed the error.

I wish you a good work and nice coding.

**Comment by iYahya** [comment] 2020-05-12 12:41
I'm using native-base
route : node_modules/native-base/basic/Picker.js

so i navigate to picker component in it and changed the import picker from 'react-native' to '@react-native-community/picker'

and everything works fine for me

**before**
![image](https://user-images.githubusercontent.com/23135076/81692366-983a0f80-945e-11ea-9a14-0b8cbaecd171.png)

**after**
![image](https://user-images.githubusercontent.com/23135076/81692072-2366d580-945e-11ea-9cff-b0b95ef5829d.png)

**Comment by haocse** [comment] 2020-05-21 05:45
+1

**Comment by haocse** [comment] 2020-05-21 06:27
Fixed for me: 
Remove `import {Picker} from '@react-native-community/picker';`
And use `import { Picker } from 'react-native`

**Comment by mrinal-roy-au2** [comment] 2020-05-22 10:20
@haocse the issue comes when we use `{ Picker }` from `@react-native-community/picker`
With `react-native` this issue doe snot arise. But with `react-native` does the `{Picker}` work in iOS ?

**Comment by haocse** [comment] 2020-05-25 08:45
@mrinal-roy-au2 Yes, iOS app works, this problem happens on the Android app

**Comment by rassemdev** [comment] 2020-05-30 21:31
@haocse Picker in React-Native is deprecated. And they are suggesting this one. So need to sort this out within it.

**Comment by sfarkas1988** [comment] 2020-06-01 10:36
Same issue here. using `import { Picker } from 'react-native'` is not a solution as suggested by @haocse

**Comment by rassemdev** [comment] 2020-06-02 20:25
anybody found any solution except importing from RN!

**Comment by introin** [comment] 2020-06-07 19:07
+1

**Comment by zouhairjabiri** [comment] 2020-06-10 01:03
Fixed for me:
Remove import { Picker } from '@react-native-community/picker';
And use import { Picker } from 'react-native'

**Comment by ShenriQ** [comment] 2020-06-13 09:56
Same Here.
Is there any solution?
I think my error comes from Picker from @react-native-community/picker and react-native-country-picker-modal

**Comment by adrian1388** [comment] 2020-06-16 02:28
May be you all still are using Picker from 'react-native' somewhere in your project.
Be sure to not import from 'react-native'

Even I can use {Picker} from '@react-native-community/picker' inside styled-components this way:

`const MyPicker = styled(Picker)...`

This was my case.

**Comment by LohanaPawan** [comment] 2020-06-16 15:15
> In my case, I used @react-native-community/picker": "^1.3.0 and "react-native-google-places-autocomplete": "^1.4.1" in my project.
> "react-native-google-places-autocomplete": "^1.4.1" used picker from react-native.
> so, occured this error.
> Perhaps, there are another pakage using picker from react-native like this in your project.

Makes sense, but could you please help to understand that how we can know exactly which dependency is in clash with the picker library and how to solve the issue.

**Comment by introin** [comment] 2020-06-16 18:00
For now, I have started using Picker from native base library and the issue appears fixed for me albeit few design issue I needed to address in such.

**Comment by saim1309** [comment] 2020-06-18 02:43
I am also facing the same issue may be for temporary basis I will use it from the react-native or native base. I am using only one picker in one of my components and the moment I import it from '@react-native-community/picker' it throws that error. 
Anyways, if anybody come across the solution, please please let us know.

**Comment by raymochi** [comment] 2020-06-18 03:51
So, I ran into this issue and got it working by changing the name of AndroidDropdownPicker to RNCAndroidDropdownPicker, did the same for dialogpicker.

I opened up a PR for the changes, you can see them here: https://github.com/react-native-community/react-native-picker/pull/99

**Comment by kesha-antonov** [comment] 2020-09-25 19:46
In my case I had 2 versions in yarn.lock

Added
```
"resolutions": {
    "@react-native-community/picker": "^1.8.0"
  },
```
to package.json to fix this

**Comment by diogoaltoe** [comment] 2020-10-09 23:16
In my case, here is the way I found to temporarily solve the problem. It is obviously not the best way, but it was the one I found at the time.

https://github.com/GeekyAnts/NativeBase/issues/3114#issuecomment-706439559

**Comment by hengkx** [comment] 2020-10-13 11:40
"@react-native-community/picker": "^1.8.1", same issue.

**Comment by grekosys** [comment] 2020-11-07 19:09
Yo tenía el mismo problema. Lo solucione desinstalando react-native-picker-select. Esté tiene conflicto con native-base.

**Comment by altany** [comment] 2020-12-08 16:03
We are importing two pickers in one scene, made sure to only import from @react-native-community/picker and not "react-native" and tried the trick with adding accessibility labels but I still get this error.

Can someone help with this as we currently have a broken app because of this.

**Comment by MehmetKaplan** [comment] 2021-01-03 09:43
> In my case I had 2 versions in yarn.lock
> 
> Added
> 
> ```
> "resolutions": {
>     "@react-native-community/picker": "^1.8.0"
>   },
> ```
> 
> to package.json to fix this

A similar approach solved my case within Expo 40 and for *datetimepicker*, not *picker*:

```
	"resolutions": {
		"@react-native-community/datetimepicker": "3.0.4"
	 },
```

**Comment by Wei102193** [comment] 2021-01-07 06:33
In my case I am using "@react-native-picker/picker": "^1.9.2", and   "native-base": "^2.13.14".
Somehow the latest version of "native-base" is using picker from "@react-native-community/picker" which  has been deprecated. I believe this is what caused the problem on my side. So I downgrade react-native to version 2.13.14 where they still import picker from native base, and It works fine. Seriously "native-base" caused too much problems, I am thinking remove it completely from my project. Hope this help someone.

**Comment by MehmetKaplan** [comment] 2021-01-07 11:35
> Seriously "native-base" caused too much problems, I am thinking remove it completely from my project. 

Even though I respect the developers of the native-base, I could not have agreed more to above comment. It is generating more problems than it solves, especially with pickers.

**Comment by nandorojo** [comment] 2021-01-10 21:18
I got a similar error upgrading from Expo SDK 39 -> 40. I solved it by uninstalling `@react-native-community/picker` and instead installing `@react-native-picker/picker`.

**Comment by gluons** [comment] 2021-01-14 04:45
Uninstall old `@react-native-community/picker` and install latest `@react-native-picker/picker` solve this problem for me.

**Comment by jdoherty61** [comment] 2021-01-16 18:42
https://github.com/react-native-picker/picker/issues/45#issuecomment-633163973

**Comment by guicompeng** [comment] 2021-01-20 16:35
https://github.com/react-native-picker/picker/issues/15#issuecomment-757545674 and https://github.com/react-native-picker/picker/issues/15#issuecomment-759922490
You saved my life today

**Comment by iguilhermeluis** [comment] 2021-01-21 13:54
> ```
>  <Picker
>   selectedValue={formik.values.gender}
>   accessibilityLabel={'gender'}
>   onValueChange={(itemValue, itemIndex) => {
>     formik.setFieldValue('gender', itemValue);
>   }}>
>   <Picker.Item label="Male" value="MALE" />
>   <Picker.Item label="Female" value="FEMALE" />
> </Picker>
> ```
> 

it work for me!

**Comment by DimanshaMalrindu** [comment] 2021-01-25 03:21
The Author renamed the library to @react-native-picker/picker.  See the GitHub new repository: https://github.com/react-native-picker/picker  It will resolve the issue after uninstalling the @react-native-community-picker library and rename the imported pickers to @react-native-picker/picker

**Comment by nayookyaw** [comment] 2021-03-03 10:01
I changed react-native-community/datetimepicker version from 

2.4.0 to 3.0.9

"@react-native-community/datetimepicker": "^3.0.9"

We can assume the old version will get error

**Comment by vijaychouhan-rails** [comment] 2021-05-22 06:50
I installed the **NativeBase** version that installed **"@react-native-picker/picker" "^1.9.7**" as dependency and by mistake, I install @react-native-picker/picker too.
**So to solve this issue:**  remove the @react-native-picker/picker that you installed because of NativeBase already installed @react-native-picker/picker as a dependency, if you are using yarn then check on yarn.lock file

**Comment by danielfein** [comment] 2021-11-30 02:57
I actually realized I didn't need native-base so I just deleted it (which I know isn't possible for everyone) and that worked. I did a little more research after and it looks like I could have upgraded native-base to the latest version and it would have worked. Hope that helps anybody struggling with this one!
